### ISSUE TITLE
Mod Menu buttons are not showing

### ISSUE THREAD

**Issue by ShidHead** [Temperz87/ultra-mod-manager#39]
The error i got from the console i got from BepinEx is the following: [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
UMM.HarmonyPatches.Inject_ModsButton.Prefix (OptionsMenuToManager __instance) (at <746c048738884d649eede6b78125b4a6>:0)
**OptionsMenuToManager.Start** () (at <a9b939e00cda4fa096ddb59b561f9d69>:0)

**Comment by Ultrakillfan** [comment]
https://github.com/Temperz87/ultra-mod-manager/issues/34
is the only thing i have to say

**Comment by Temperz87** [comment]
See above comment
