### ISSUE TITLE
RetrieveXPersistentModData methods dont work correctly

### ISSUE THREAD

**Issue by nota8ot** [Temperz87/ultra-mod-manager#7]
RetrieveIntPersistentModData, RetrieveBooleanPersistentModData, RetrieveFloatPersistentModData, etc call RetrieveStringPersistentModData with the wrong parameters (modName, key) when it should be (key, modName)

**Comment by Temperz87** [comment]
I am so sorry, I have fixed this, see releaes 0.4.3 of UMM.
